name: haiti_lotri
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: 5.0.0-release-candidate-9.3.2
  sizing: ^1.1.2
  intl: any
  mask_text_input_formatter: ^2.9.0
  loading_animation_widget: ^1.3.0
  flutter_cache_manager: ^3.4.1
  get_storage_pro: ^0.1.9
  pin_code_fields: ^8.0.1
  syncfusion_flutter_gauges: ^28.1.38
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.4
  flutter_localizations:
    sdk: flutter
  custom_image_crop: ^0.1.1
  file_picker: ^9.0.1
  image_picker: ^1.1.2
  mime: ^2.0.0
  cached_network_image: ^3.4.1
  firebase_core: ^3.12.1
  firebase_notifications_handler: ^2.0.2+1
  firebase_messaging: ^15.2.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  loon: ^5.1.2
  flutter_launcher_icons: ^0.14.3
  flutter_rename_app_plus3: ^1.2.4
  package_rename: ^1.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/appIcons/
    - assets/images/
  fonts:
    - family: Kiwoo
      fonts:
        - asset: assets/fonts/kiwoo.ttf
    - family: Poppins-Thin
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
    - family: Poppins-ThinItalic
      fonts:
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
    - family: Poppins-ExtraLight
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
    - family: Poppins-ExtraLightItalic
      fonts:
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
    - family: Poppins-LightItalic
      fonts:
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: Poppins-Italic
      fonts:
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
    - family: Poppins-MediumItalic
      fonts:
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: Poppins-SemiBoldItalic
      fonts:
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Poppins-BoldItalic
      fonts:
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
    - family: Poppins-ExtraBold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
    - family: Poppins-ExtraBoldItalic
      fonts:
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
    - family: Poppins-Black
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
    - family: Poppins-BlackItalic
      fonts:
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
  

  
