// ignore_for_file: constant_identifier_names

import 'package:flutter/src/widgets/framework.dart';
import 'package:get/get.dart';

class AppStrings {
  static String LOG_IN = 'LOG_IN'.tr;
  static String REGISTER = 'REGISTER'.tr;
  static String RESET_PASSWORD = 'RESET_PASSWORD'.tr;
  static String RESET = 'RESET'.tr;
  static String SIGN_UP_NOW = 'SIGN_UP_NOW'.tr;
  static String SIGN_UP = 'SIGN_UP'.tr;
  static String VERIFY_PHONE_NUMBER = 'VERIFY_PHONE_NUMBER'.tr;
  static String VERIFY_EMAIL = 'VERIFY_EMAIL'.tr;
  static String CONTINUE = 'CONTINUE'.tr;
  static String RESEND_CODE_BTN = 'RESEND_CODE_BTN'.tr;
  static String CHAT_BTN = 'CHAT_BTN'.tr;
  static String ACCEPT = 'ACCEPT'.tr;
  static String REJECT = 'REJECT'.tr;
  static String SAVE = 'SAVE'.tr;
  static String PASSWORD_INVALID = 'PASSWORD_INVALID'.tr;
  static String PASSWORD_MIN_LOWERCASE = 'PASSWORD_MIN_LOWERCASE'.tr;
  static String PASSWORD_MIN_UPPERCASE = 'PASSWORD_MIN_UPPERCASE'.tr;
  static String PASSWORD_MIN_NUMBERS = 'PASSWORD_MIN_NUMBERS'.tr;
  static String PASSWORD_MIN_SYMBOLS = 'PASSWORD_MIN_SYMBOLS'.tr;
  static String PASSWORD_MAX_LENGTH = 'PASSWORD_MAX_LENGTH'.tr;
  static String APP_NAME = 'APP_NAME'.tr;
  static String SLOGAN = 'SLOGAN'.tr;
  static String WELCOME = 'WELCOME'.tr;
  static String FORGOT_PASSWORD = 'FORGOT_PASSWORD'.tr;
  static String FORGOT_PASSWORD2 = 'FORGOT_PASSWORD2'.tr;
  static String CREATE_NEW_PASSWORD = 'CREATE_NEW_PASSWORD'.tr;
  static String NEW_USER = 'NEW_USER'.tr;
  static String BACK_TO = 'BACK_TO'.tr;
  static String REGISTER_HERE = 'REGISTER_HERE'.tr;
  static String ALREADY_HAVE_AN_ACCOUNT = 'ALREADY_HAVE_AN_ACCOUNT'.tr;
  static String LOGIN = 'LOGIN'.tr;
  static String OTP = 'OTP'.tr;
  static String CODE_IS_SENT_TO = 'CODE_IS_SENT_TO'.tr;
  static String RESEND_CODE = 'RESEND_CODE'.tr;
  static String SERVICE_AT_YOU_FINGERTIPS = 'SERVICE_AT_YOU_FINGERTIPS'.tr;
  static String FOR_ANY_ASSISTANCE_PLEASE = 'FOR_ANY_ASSISTANCE_PLEASE'.tr;
  static String CALL = 'CALL'.tr;
  static String EMAIL = 'EMAIL'.tr;
  static String PASSWORD = 'PASSWORD'.tr;
  static String NAME = 'NAME'.tr;
  static String PHONE_NUMBER = 'PHONE_NUMBER'.tr;
  static String SEARCH = 'SEARCH'.tr;
  static String ENTER_DURATION = 'ENTER_DURATION'.tr;
  static String ENTER_OLD_PASSWORD = 'ENTER_OLD_PASSWORD'.tr;
  static String ENTER_NEW_PASSWORD = 'ENTER_NEW_PASSWORD'.tr;
  static String ENTER_CONFIRM_NEW_PASSWORD = 'ENTER_CONFIRM_NEW_PASSWORD'.tr;
  static String OLD_PASSWORD = 'OLD_PASSWORD'.tr;
  static String NEW_PASSWORD = 'NEW_PASSWORD'.tr;
  static String CONFIRM_NEW_PASSWORD = 'CONFIRM_NEW_PASSWORD'.tr;
  static String PLS_ENTER_EMAILID = 'PLS_ENTER_EMAILID'.tr;
  static String PLS_ENTER_VALID_EMAILID = 'PLS_ENTER_VALID_EMAILID'.tr;
  static String PLS_ENTER_VALID_EMAIL = 'PLS_ENTER_VALID_EMAIL'.tr;
  static String PLS_ENTER_EMAIL = 'PLS_ENTER_EMAIL'.tr;
  static String PLS_ENTER_MESSAGE = 'PLS_ENTER_MESSAGE'.tr;
  static String PLS_ENTER_PASSWORD = 'PLS_ENTER_PASSWORD'.tr;
  static String PLS_ENTER_CONFIRM_PASSWORD = 'PLS_ENTER_CONFIRM_PASSWORD'.tr;
  static String PLS_ENTER_PASSWORD_MUST_BE_LONG =
      'PLS_ENTER_PASSWORD_MUST_BE_LONG'.tr;
  static String PLS_ENTER_PASSWORD_NOT_MATCH = 'PLS_ENTER_OT_MATCH'.tr;
  static String PLS_ENTER_NAME = 'PLS_ENTER_NAME'.tr;
  static String PLS_ENTER_PHONE_NUMBER = 'PLS_ENTER_PHONE_NUMBER'.tr;
  static String PLS_ENTER_VALID_PHONE_NUMBER =
      'PLS_ENTER_VALID_PHONE_NUMBER'.tr;
  static String PLS_ENTER_VALID_H_PHONE_NUMBER =
      'PLS_ENTER_VALID_H_PHONE_NUMBER'.tr;
  static String PLS_ENTER_OTP = 'PLS_ENTER_OTP'.tr;
  static String PLS_ENTER_VALID_OTP = 'PLS_ENTER__VALID_OTP'.tr;
  static String PLS_ENTER_PIN = 'PLS_ENTER_PIN'.tr;
  static String onEmpty = 'onEmpty'.tr;
  static String STAR_SIGN = 'STAR_SIGN'.tr;
  static String NO_DATA_FOUND = 'NO_DATA_FOUND'.tr;
  static String ENTER_AMOUNT = 'ENTER_AMOUNT'.tr;
  static String ADDRESS_MARKET_DETAILS = 'ADDRESS_MARKET_DETAILS'.tr;
  static String CONTACTS = 'CONTACTS'.tr;
  static String AMOUNT = 'AMOUNT'.tr;
  static String E_G_8_OR_12 = 'E_G_8_OR_12'.tr;
  static String E_G_12_OR_24 = 'E_G_12_OR_24'.tr;
  static String SUBMIT = 'SUBMIT'.tr;
  static String PAYMENT_REQUEST = 'PAYMENT_REQUEST'.tr;
  static String SEND = 'SEND'.tr;
  static String SEND_EMAIL = 'SEND_EMAIL'.tr;
  static String CREATE_PASSWORD = 'CREATE_PASSWORD'.tr;
  static String EDIT_PROFILE = 'EDIT_PROFILE'.tr;
  static String PLS_ENTER_AMOUNT = 'PLS_ENTER_AMOUNT'.tr;
  static String PLEASE_ENTER_OLD_PASSWORD = 'PLEASE_ENTER_OLD_PASSWORD'.tr;
  static String PLEASE_ENTER_NEW_PASSWORD = 'PLEASE_ENTER_NEW_PASSWORD'.tr;
  static String PLEASE_ENTER_CONFIRM_NEW_PASSWORD =
      'PLEASE_ENTER_CONFIRM_NEW_PASSWORD'.tr;
  static String DOES_NOT_MATCH_CONFIRM_PASSWORD =
      'DOES_NOT_MATCH_CONFIRM_PASSWORD'.tr;
  static String PLS_MIN_AMOUNT = 'PLS_MIN_AMOUNT'.tr;
  static String PLS_ENTER_INCOME = 'PLS_ENTER_INCOME'.tr;
  static String PLS_ENTER_OCCUPATION = 'PLS_ENTER_OCCUPATION'.tr;
  static String PLS_ENTER_ADDRESS = 'PLS_ENTER_ADDRESS'.tr;
  static String PLS_ENTER_STATE = 'PLS_ENTER_STATE'.tr;
  static String PLS_ENTER_CITY = 'PLS_ENTER_CITY'.tr;
  static String PLS_ENTER_COUNTRY = 'PLS_ENTER_COUNTRY'.tr;
  static String PLS_ENTER_ZIPCODE = 'PLS_ENTER_ZIPCODE'.tr;
  static String GENERAL_CHAT = 'GENERAL_CHAT'.tr;
  static String PROFILE = 'PROFILE'.tr;
  static String CHANGE_PASSWORD = 'CHANGE_PASSWORD'.tr;
  static String ADDRESS = 'ADDRESS'.tr;
  static String IDENTITY_VERIFICATION = 'IDENTITY_VERIFICATION'.tr;
  static String INCOME_VERIFICATION = 'INCOME_VERIFICATION'.tr;
  static String OCCUPATION_VERIFICATION = 'OCCUPATION_VERIFICATION'.tr;
  static String TRANSACTIONS = 'TRANSACTIONS'.tr;
  static String IS_TYPING = 'IS_TYPING'.tr;
  static String CONNECTING = 'CONNECTING'.tr;
  static String SUBMITTED_SUCCESSFULLY = 'SUBMITTED_SUCCESSFULLY'.tr;
  static String RECEIVED_REQUEST = 'RECEIVED_REQUEST'.tr;
  static String MONEY_THAT_YOU_HAVE_BORROWED_FROM_OTHERS =
      'MONEY_THAT_YOU_HAVE_BORROWED_FROM_OTHERS'.tr;
  static String MONEY_THAT_YOU_HAVE_LET_OTHER_PEOPLE_BORROW =
      'MONEY_THAT_YOU_HAVE_LET_OTHER_PEOPLE_BORROW'.tr;
  static String UPDATE_BALANCE = 'UPDATE_BALANCE'.tr;
  static String ABOUT_US = 'ABOUT_US'.tr;
  static String PRIVACY_POLICY = 'PRIVACY_POLICY'.tr;
  static String TERMS_OF_USE = 'TERMS_OF_USE'.tr;
  static String HELP_CENTER = 'HELP_CENTER'.tr;
  static String MESAJ = 'MESAJ'.tr;
  static String ENTER_MESSAGE = 'ENTER_MESSAGE'.tr;
  static String ENTER_EMAIL = 'ENTER_EMAIL'.tr;
  static String ENTER_NAME = 'ENTER_NAME'.tr;
  static String ENTER_CITY = 'ENTER_CITY'.tr;
  static String ENTER_STATE = 'ENTER_STATE'.tr;
  static String ENTER_PINCODE = 'ENTER_PINCODE'.tr;
  static String ENTER_ZIPCODE = 'ENTER_ZIPCODE'.tr;
  static String ENTER_ADDRESS = 'ENTER_ADDRESS'.tr;
  static String ENTER_COUNTRY = 'ENTER_COUNTRY'.tr;
  static String ENTER_AGE = 'ENTER_AGE'.tr;
  static String ENTER_OCCUPATION = 'ENTER_OCCUPATION'.tr;
  static String ENTER_INCOME = 'ENTER_INCOME'.tr;
  static String AGE = 'AGE'.tr;
  static String OCCUPATION = 'OCCUPATION'.tr;
  static String REVNI = 'REVNI'.tr;
  static String CITY = 'CITY'.tr;
  static String ETA = 'ETA'.tr;
  static String COUNTRY = 'COUNTRY'.tr;
  static String PINCODE = 'PINCODE'.tr;
  static String ZIPCODE = 'ZIPCODE'.tr;
  static String NOTIFICATION = 'NOTIFICATION'.tr;

  static String PASSWORD_NOT_MATCH = "PASSWORD_NOT_MATCH".tr;
}
