// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
import 'dart:core';
import 'package:get_storage_pro/src/gsp.dart' as prefix0;
import 'package:haiti_lotri/app/data/models/user_model.dart' as prefix1;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import

import 'package:reflectable/mirrors.dart' as m;
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.GetStorageProReflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'CurrentUser',
            r'.CurrentUser',
            134217735,
            0,
            const prefix0.GetStorageProReflector(),
            const <int>[0, 1, 2, 3, 4, 5, 6, 11, 12, 13, 14, 15],
            const <int>[6, 5, 16, 12, 17, 2, 3, 4, 7, 8, 9, 10, 11],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => ({userDetails, unReadNotification = 0}) => b
                  ? prefix1.CurrentUser(
                      unReadNotification: unReadNotification,
                      userDetails: userDetails)
                  : null,
              r'fromMap': (bool b) =>
                  (map) => b ? prefix1.CurrentUser.fromMap(map) : null,
              r'fromJson': (bool b) =>
                  (source) => b ? prefix1.CurrentUser.fromJson(source) : null
            },
            0,
            0,
            const <int>[],
            const <Object>[prefix0.gsp],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'userDetails', 67239941, 0,
            const prefix0.GetStorageProReflector(), -1, -1, -1, null, const []),
        r.VariableMirrorImpl(r'unReadNotification', 134348805, 0,
            const prefix0.GetStorageProReflector(), -1, -1, -1, null, const []),
        r.MethodMirrorImpl(
            r'copyWith',
            2097154,
            0,
            0,
            -1,
            -1,
            null,
            const <int>[0, 1],
            const prefix0.GetStorageProReflector(),
            const []),
        r.MethodMirrorImpl(
            r'toMap',
            35651586,
            0,
            -1,
            -1,
            -1,
            null,
            const <int>[],
            const prefix0.GetStorageProReflector(),
            const <Object>[override]),
        r.MethodMirrorImpl(r'toJson', 2097154, 0, -1, -1, -1, null,
            const <int>[], const prefix0.GetStorageProReflector(), const []),
        r.MethodMirrorImpl(
            r'toString',
            2097154,
            0,
            -1,
            -1,
            -1,
            null,
            const <int>[],
            const prefix0.GetStorageProReflector(),
            const <Object>[override]),
        r.MethodMirrorImpl(r'==', 2097154, 0, -1, -1, -1, null, const <int>[2],
            const prefix0.GetStorageProReflector(), const <Object>[override]),
        r.ImplicitGetterMirrorImpl(
            const prefix0.GetStorageProReflector(), 0, 7),
        r.ImplicitSetterMirrorImpl(
            const prefix0.GetStorageProReflector(), 0, 8),
        r.ImplicitGetterMirrorImpl(
            const prefix0.GetStorageProReflector(), 1, 9),
        r.ImplicitSetterMirrorImpl(
            const prefix0.GetStorageProReflector(), 1, 10),
        r.MethodMirrorImpl(r'id', 2097155, 0, -1, -1, -1, null, const <int>[],
            const prefix0.GetStorageProReflector(), const <Object>[override]),
        r.MethodMirrorImpl(
            r'hashCode',
            2097155,
            0,
            -1,
            -1,
            -1,
            null,
            const <int>[],
            const prefix0.GetStorageProReflector(),
            const <Object>[override]),
        r.MethodMirrorImpl(r'', 0, 0, -1, -1, -1, null, const <int>[3, 4],
            const prefix0.GetStorageProReflector(), const []),
        r.MethodMirrorImpl(r'fromMap', 1, 0, -1, -1, -1, null, const <int>[5],
            const prefix0.GetStorageProReflector(), const []),
        r.MethodMirrorImpl(r'fromJson', 1, 0, -1, -1, -1, null, const <int>[6],
            const prefix0.GetStorageProReflector(), const []),
        r.MethodMirrorImpl(r'noSuchMethod', 524290, -1, -1, -1, -1, null,
            const <int>[9], const prefix0.GetStorageProReflector(), const []),
        r.MethodMirrorImpl(r'runtimeType', 2097155, -1, -1, -1, -1, null,
            const <int>[], const prefix0.GetStorageProReflector(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'userDetails',
            67252230,
            2,
            const prefix0.GetStorageProReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            #userDetails),
        r.ParameterMirrorImpl(
            r'unReadNotification',
            67252230,
            2,
            const prefix0.GetStorageProReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            #unReadNotification),
        r.ParameterMirrorImpl(
            r'other',
            134348806,
            6,
            const prefix0.GetStorageProReflector(),
            0,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'userDetails',
            67253254,
            13,
            const prefix0.GetStorageProReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            #userDetails),
        r.ParameterMirrorImpl(
            r'unReadNotification',
            134364166,
            13,
            const prefix0.GetStorageProReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            0,
            #unReadNotification),
        r.ParameterMirrorImpl(
            r'map',
            151126022,
            14,
            const prefix0.GetStorageProReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'source',
            134348806,
            15,
            const prefix0.GetStorageProReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_userDetails',
            67240038,
            8,
            const prefix0.GetStorageProReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_unReadNotification',
            134348902,
            10,
            const prefix0.GetStorageProReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            134348806,
            16,
            const prefix0.GetStorageProReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null)
      ],
      <Type>[prefix1.CurrentUser],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'copyWith': (dynamic instance) => instance.copyWith,
        r'toMap': (dynamic instance) => instance.toMap,
        r'toJson': (dynamic instance) => instance.toJson,
        r'userDetails': (dynamic instance) => instance.userDetails,
        r'unReadNotification': (dynamic instance) =>
            instance.unReadNotification,
        r'id': (dynamic instance) => instance.id
      },
      {
        r'userDetails=': (dynamic instance, value) =>
            instance.userDetails = value,
        r'unReadNotification=': (dynamic instance, value) =>
            instance.unReadNotification = value
      },
      <m.LibraryMirror>[
        r.LibraryMirrorImpl(
            r'',
            Uri.parse('package:haiti_lotri/app/data/models/user_model.dart'),
            const prefix0.GetStorageProReflector(),
            const <int>[],
            {},
            {},
            const [],
            null)
      ],
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
